### ISSUE TITLE
Plugin dependencies 

### ISSUE THREAD

**Issue by chens2i** [wiris/moodle-qtype_matchwiris#36]
Hi I Just try to upgrade the matching wiris plugin to the latest version, it reuqires that qtype_wq version at least 2023092200, but the latest version of qtype_wq is 2023050202.

Please fix,

**Comment by chens2i** [comment]
Update:
I found the latest release from github repo, but not from moodle plugin repo
https://moodle.org/plugins/qtype_wq

**Comment by ptorrent-at-wiris** [comment]
Hi, apologies for the delay in responding. Dependencies should be working correctly now. Best,
